name: Shashank Sharma
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

title: Shashank Sharma
description: > # this means to ignore newlines until "baseurl:"
  Shashank Sharma: Self Driving Car and Robotics Engineer.
  Ph.D. in Mechanical Engineering at Stony Brook University.
url: "https://sharmashashank.com"
author: Shashank Sharma

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
